# Generated by Django 5.2.7 on 2025-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
