# Generated by Django 5.2.7 on 2025-11-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_customer_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
