# Generated by Django 5.2.7 on 2025-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
