# Generated by Django 5.2.7 on 2025-11-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_payment_expired_at_payment_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('mobile_payment', 'Mobile Payment')], default='cash', max_length=20),
        ),
    ]
