# Generated by Django 5.2.7 on 2025-12-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
