# Generated by Django 5.2.7 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_image_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('product', 'image_hash'), name='unique_image_per_product'),
        ),
    ]
