# Generated by Django 5.2.7 on 2026-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_invoice_invoice_date_invoice_status_table_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_menu_active',
            field=models.BooleanField(default=True),
        ),
    ]
