from api.serializers.auth.register_serializer import RegisterSerializer,LoginSerializer
from api.serializers.category.category_serializer import CategorySerializer
from api.serializers.product.product_serializer import ProductSerializer,ImageSerializer
from api.serializers.table.table_serializer import TableSerializer
from api.serializers.reservation.reservation_serializer import ReservationSerializer,ReservationSerializerAdmin
from api.serializers.cartitem.cartitem_serializer import CartItemSerializer
from api.serializers.order.order_serializer import CreateOrderSerializer,OrderSerializer