from api.serializers.auth.register_serializer import RegisterSerializer,LoginSerializer
from api.serializers.category.category_serializer import CategorySerializer
from api.serializers.product.product_serializer import ProductSerializer,ImageSerializer
from api.serializers.table.table_serializer import TableSerializer
from api.serializers.reservation.reservation_serializer import ReservationSerializer,ReservationSerializerAdmin
from api.serializers.cartitem.cartitem_serializer import CartItemSerializer, CartSerializer
from api.serializers.order.order_serializer import CreateOrderSerializer,OrderSerializer
from api.serializers.invoice import invoice_serializer
#
from api.serializers.user.user_serializer import UserSerializer
from api.serializers.user.staff_update_serializer import StaffUpdateSerializer